### ISSUE TITLE
Feature Request: MQTT availability_topic

### ISSUE THREAD

**Issue by SurfingSpider** [stelgenhof/AiLight#35]
Can I ask if we can get the availability_topic working. So if the bulb is off it shows as unavailable in home assistant. hopefully if home assistant restart it will also show the current status of the lamp.

[https://www.home-assistant.io/components/light.mqtt/#availability_topic](https://www.home-assistant.io/components/light.mqtt/#availability_topic)

I have it working on my tasmota sonoff switches and it is very handy to see if one of them goes offline

**Comment by stelgenhof** [comment]
Absolutely! Let me have a look how to implement that :)

**Comment by SurfingSpider** [comment]
I see on the front page that you have enabled MQTT Last Will and Testament maybe this is all i need. just put it in the availability topic. I cant find any info on the wiki on how to implement it.

When I setup a device in home assistant (mosquitto Mqtt) which has **tasmota firmware** on it my configuration.h looks like this.....

```
light:
  - platform: mqtt
    name: "Fireplace" 
    state_topic: "stat/sonoff7/POWER" 
    command_topic: "cmnd/sonoff7/power" 
    availability_topic: "tele/sonoff7/LWT"    
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
```

I assume that the availability_topic would be the Status Topic in the AiLight UI. and the Payload_on, Payload_off, Payload_availible, Payload_Not_available would be the responses AiLight gives over MQTT

Do you think I could be close to the mark?

**Comment by mjoshd** [comment]
I didn't have to do anything special for the LWT online/offline messages to
work. About 30-60 seconds after the bulbs lose power, the MQTT broker will
send the "offline" message and moments after power is restored the "online"
message is sent.

Here is what I have in my config-

light:
- platform: mqtt_json
name: My Lamp
state_topic: "hassio/ailight/my_lamp"
command_topic: "hassio/ailight/my_lamp/set"
color_temp: true
brightness: true
rgb: true
white_value: true
effect: false
optimistic: false

**Comment by mjoshd** [comment]
I didn't have to do anything special for the LWT online/offline messages to
work. About 30-60 seconds after the bulbs lose power, the MQTT broker will
send the "offline" message and moments after power is restored the "online"
message is sent.

Here is what I have in my config-

```
light:
  - platform: mqtt_json
    name: My Lamp
    state_topic: "hassio/ailight/my_lamp"
    command_topic: "hassio/ailight/my_lamp/set"
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
```
