### ISSUE TITLE
Freezes for a couple of mins when firing quick MQTT

### ISSUE THREAD

**Issue by badgerhome** [stelgenhof/AiLight#39]
Hi,

I'm testing 0.6.0-dev, I'm using it with this script: https://community.home-assistant.io/t/finally-a-cheap-wireless-switch-that-dims-xiaomi-switch-gen1/27574

Which basically fires a dim command in a loop until a button press is released:
```
service: light.turn_on
        entity_id: light.landing_light
        data_template:
          brightness: '{{states.light.landing_light.attributes.brightness - 10}}'
```
I've noticed that 0.6.0-dev freezes up for a couple of mins and then comes back, I can still access thr bulb via HTTP but can't issue any commands, I've downgraded the bulb to 0.5.1-dev and it seems to be working fine.

Sorry I can't provide any more details, I'll carry out doing some more testing. Let me know if there's anything else useful I can share.

Cheers!
